appium_config:
  "platformName": "Android"
  "deviceName": "Redmi"
  "platformVersion": "9.0"
  "appPackage": "im.artemis.fawn.staging"
  "appActivity": "im.artemis.fawn.MainActivity"
  "unicodeKeyboard": True
  "resetKeyboard": True